// BIKE

export const enum BikeMaker {
  yamaha = "Yamaha",
  honda = "honda",
  bajaj = "Bajaj",
}
export const enum YamahaModels {
  fazzio = "Fazzio",
  vmax = "Vmax",
  ray = "Ray",
  xsr = "Xsr",
}
export const enum hondaModels {
  activa = "Activa",
  shine = "Shine",
  navi = "Navi",
  dio = "Dio",
}

export const enum BajajModels {
  pulsar = "Pulsar",
  platina = "Platina",
  dominar = "Dominar",
  CT = "CT",
}

export const BikeInsuranceDekho = [
  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2019",
    premiumAmount: 650,
    idv: 700890,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2019",
    premiumAmount: 500,
    idv: 80000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2020",
    premiumAmount: 700,
    idv: 7015,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2020",
    premiumAmount: 650,
    idv: 15900,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2019",
    premiumAmount: 950,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2019",
    premiumAmount: 742,
    idv: 21300,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2020",
    premiumAmount: 950,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2020",
    premiumAmount: 7420,
    idv: 213000,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2019",
    premiumAmount: 900,
    idv: 20000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2019",
    premiumAmount: 840,
    idv: 10300,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2020",
    premiumAmount: 910,
    idv: 20000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2020",
    premiumAmount: 8200,
    idv: 113000,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2019",
    premiumAmount: 702,
    idv: 23090,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2019",
    premiumAmount: 402,
    idv: 13090,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2020",
    premiumAmount: 802,
    idv: 28090,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2020",
    premiumAmount: 502,
    idv: 135090,
    policy: "Third Party",
  },

  // honda

  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2019",
    premiumAmount: 700,
    idv: 20000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2019",
    premiumAmount: 500,
    idv: 15000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2020",
    premiumAmount: 850,
    idv: 28900,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2020",
    premiumAmount: 650,
    idv: 15900,
    policy: "Third Party",
  },

  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2019",
    premiumAmount: 950,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2019",
    premiumAmount: 742,
    idv: 21300,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2020",
    premiumAmount: 950,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2020",
    premiumAmount: 742,
    idv: 21300,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2019",
    premiumAmount: 900,
    idv: 20000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2019",
    premiumAmount: 840,
    idv: 10300,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2020",
    premiumAmount: 910,
    idv: 20000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2020",
    premiumAmount: 820,
    idv: 11300,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2019",
    premiumAmount: 702,
    idv: 23090,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2019",
    premiumAmount: 402,
    idv: 13090,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2020",
    premiumAmount: 802,
    idv: 28090,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2020",
    premiumAmount: 502,
    idv: 135090,
    policy: "Third Party",
  },

  // bajaj

  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2019",
    premiumAmount: 700,
    idv: 20000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2019",
    premiumAmount: 500,
    idv: 15000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2020",
    premiumAmount: 850,
    idv: 28900,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2020",
    premiumAmount: 650,
    idv: 15900,
    policy: "Third Party",
  },

  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2019",
    premiumAmount: 950,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2019",
    premiumAmount: 742,
    idv: 21300,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2020",
    premiumAmount: 950,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2020",
    premiumAmount: 742,
    idv: 21300,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2019",
    premiumAmount: 900,
    idv: 20000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2019",
    premiumAmount: 840,
    idv: 10300,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2020",
    premiumAmount: 9100,
    idv: 200000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2020",
    premiumAmount: 820,
    idv: 11300,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2019",
    premiumAmount: 702,
    idv: 23090,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2019",
    premiumAmount: 402,
    idv: 13090,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2020",
    premiumAmount: 802,
    idv: 28090,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2020",
    premiumAmount: 502,
    idv: 21009,
    policy: "Third Party",
  },
];

// BIKE POlicy BAzar

export const BikePolicyBazar = [
  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2019",
    premiumAmount: 750,
    idv: 770890,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2019",
    premiumAmount: 400,
    idv: 70000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2020",
    premiumAmount: 800,
    idv: 7215,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2020",
    premiumAmount: 600,
    idv: 15000,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2019",
    premiumAmount: 900,
    idv: 32000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2019",
    premiumAmount: 782,
    idv: 21300,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2020",
    premiumAmount: 900,
    idv: 32000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2020",
    premiumAmount: 7420,
    idv: 93000,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2019",
    premiumAmount: 940,
    idv: 50000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2019",
    premiumAmount: 850,
    idv: 12300,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2020",
    premiumAmount: 950,
    idv: 26000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2020",
    premiumAmount: 8500,
    idv: 123000,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2019",
    premiumAmount: 772,
    idv: 25090,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2019",
    premiumAmount: 400,
    idv: 13000,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2020",
    premiumAmount: 882,
    idv: 29090,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2020",
    premiumAmount: 500,
    idv: 130090,
    policy: "Third Party",
  },

  // honda

  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2019",
    premiumAmount: 750,
    idv: 23000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2019",
    premiumAmount: 550,
    idv: 17000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2020",
    premiumAmount: 890,
    idv: 29200,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2020",
    premiumAmount: 640,
    idv: 15400,
    policy: "Third Party",
  },

  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2019",
    premiumAmount: 940,
    idv: 31300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2019",
    premiumAmount: 702,
    idv: 20300,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2020",
    premiumAmount: 970,
    idv: 32400,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2020",
    premiumAmount: 752,
    idv: 23300,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2019",
    premiumAmount: 950,
    idv: 23000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2019",
    premiumAmount: 850,
    idv: 11300,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2020",
    premiumAmount: 900,
    idv: 18000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2020",
    premiumAmount: 800,
    idv: 10300,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2019",
    premiumAmount: 722,
    idv: 23190,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2019",
    premiumAmount: 412,
    idv: 13190,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2020",
    premiumAmount: 822,
    idv: 28290,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2020",
    premiumAmount: 512,
    idv: 135190,
    policy: "Third Party",
  },

  // bajaj

  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2019",
    premiumAmount: 750,
    idv: 21000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2019",
    premiumAmount: 520,
    idv: 16000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2020",
    premiumAmount: 880,
    idv: 29100,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2020",
    premiumAmount: 600,
    idv: 15000,
    policy: "Third Party",
  },

  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2019",
    premiumAmount: 900,
    idv: 32000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2019",
    premiumAmount: 702,
    idv: 20300,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2020",
    premiumAmount: 900,
    idv: 32000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2020",
    premiumAmount: 702,
    idv: 20300,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2019",
    premiumAmount: 920,
    idv: 22000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2019",
    premiumAmount: 800,
    idv: 10000,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2020",
    premiumAmount: 9200,
    idv: 230000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2020",
    premiumAmount: 800,
    idv: 10300,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2019",
    premiumAmount: 701,
    idv: 21090,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2019",
    premiumAmount: 432,
    idv: 13490,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2020",
    premiumAmount: 892,
    idv: 28490,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2020",
    premiumAmount: 500,
    idv: 20009,
    policy: "Third Party",
  },
];

// hDFC Ergo

export const HdfcErgo = [
  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2019",
    premiumAmount: 700,
    idv: 80000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2019",
    premiumAmount: 560,
    idv: 90000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2020",
    premiumAmount: 850,
    idv: 70569,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2020",
    premiumAmount: 650,
    idv: 19500,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2019",
    premiumAmount: 950,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2019",
    premiumAmount: 900,
    idv: 31300,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2020",
    premiumAmount: 362,
    idv: 52356,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2020",
    premiumAmount: 742,
    idv: 31300,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2019",
    premiumAmount: 896,
    idv: 60000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2019",
    premiumAmount: 856,
    idv: 30000,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2020",
    premiumAmount: 910,
    idv: 89000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2020",
    premiumAmount: 820,
    idv: 71000,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2019",
    premiumAmount: 902,
    idv: 23010,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2019",
    premiumAmount: 402,
    idv: 15090,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2020",
    premiumAmount: 802,
    idv: 29090,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2020",
    premiumAmount: 592,
    idv: 35090,
    policy: "Third Party",
  },

  // honda

  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2019",
    premiumAmount: 900,
    idv: 60000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2019",
    premiumAmount: 600,
    idv: 19000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2020",
    premiumAmount: 850,
    idv: 28900,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2020",
    premiumAmount: 650,
    idv: 15900,
    policy: "Third Party",
  },

  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2019",
    premiumAmount: 950,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2019",
    premiumAmount: 782,
    idv: 21900,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2020",
    premiumAmount: 950,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2020",
    premiumAmount: 942,
    idv: 25300,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2019",
    premiumAmount: 900,
    idv: 20000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2019",
    premiumAmount: 840,
    idv: 10300,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2020",
    premiumAmount: 810,
    idv: 90000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2020",
    premiumAmount: 1020,
    idv: 11200,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2019",
    premiumAmount: 702,
    idv: 23090,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2019",
    premiumAmount: 492,
    idv: 19090,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2020",
    premiumAmount: 802,
    idv: 28090,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2020",
    premiumAmount: 502,
    idv: 135090,
    policy: "Third Party",
  },

  // bajaj

  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2019",
    premiumAmount: 700,
    idv: 20000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2019",
    premiumAmount: 500,
    idv: 95000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2020",
    premiumAmount: 1050,
    idv: 30900,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2020",
    premiumAmount: 950,
    idv: 25900,
    policy: "Third Party",
  },

  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2019",
    premiumAmount: 1050,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2019",
    premiumAmount: 2042,
    idv: 31300,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2020",
    premiumAmount: 950,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2020",
    premiumAmount: 742,
    idv: 91300,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2019",
    premiumAmount: 900,
    idv: 80000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2019",
    premiumAmount: 840,
    idv: 70300,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2020",
    premiumAmount: 9100,
    idv: 200000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2020",
    premiumAmount: 520,
    idv: 91300,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2019",
    premiumAmount: 702,
    idv: 23090,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2019",
    premiumAmount: 802,
    idv: 63090,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2020",
    premiumAmount: 902,
    idv: 58090,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2020",
    premiumAmount: 2002,
    idv: 91009,
    policy: "Third Party",
  },
];

export const BikeHdfcErgo = [
  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2019",
    premiumAmount: 700,
    idv: 80000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2019",
    premiumAmount: 560,
    idv: 90000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2020",
    premiumAmount: 850,
    idv: 70569,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: BikeMaker.yamaha,
    model: YamahaModels.fazzio,
    year: "2020",
    premiumAmount: 650,
    idv: 19500,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2019",
    premiumAmount: 950,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2019",
    premiumAmount: 900,
    idv: 31300,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2020",
    premiumAmount: 362,
    idv: 52356,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.yamaha,
    model: YamahaModels.vmax,
    year: "2020",
    premiumAmount: 742,
    idv: 31300,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2019",
    premiumAmount: 896,
    idv: 60000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2019",
    premiumAmount: 856,
    idv: 30000,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2020",
    premiumAmount: 910,
    idv: 89000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.ray,
    year: "2020",
    premiumAmount: 820,
    idv: 71000,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2019",
    premiumAmount: 902,
    idv: 23010,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2019",
    premiumAmount: 402,
    idv: 15090,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2020",
    premiumAmount: 802,
    idv: 29090,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.yamaha,
    model: YamahaModels.xsr,
    year: "2020",
    premiumAmount: 592,
    idv: 35090,
    policy: "Third Party",
  },

  // honda

  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2019",
    premiumAmount: 900,
    idv: 60000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2019",
    premiumAmount: 600,
    idv: 19000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2020",
    premiumAmount: 850,
    idv: 28900,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: BikeMaker.honda,
    model: hondaModels.activa,
    year: "2020",
    premiumAmount: 650,
    idv: 15900,
    policy: "Third Party",
  },

  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2019",
    premiumAmount: 950,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2019",
    premiumAmount: 782,
    idv: 21900,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2020",
    premiumAmount: 950,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.honda,
    model: hondaModels.shine,
    year: "2020",
    premiumAmount: 942,
    idv: 25300,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2019",
    premiumAmount: 900,
    idv: 20000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2019",
    premiumAmount: 840,
    idv: 10300,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2020",
    premiumAmount: 810,
    idv: 90000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.navi,
    year: "2020",
    premiumAmount: 1020,
    idv: 11200,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2019",
    premiumAmount: 702,
    idv: 23090,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2019",
    premiumAmount: 492,
    idv: 19090,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2020",
    premiumAmount: 802,
    idv: 28090,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.honda,
    model: hondaModels.dio,
    year: "2020",
    premiumAmount: 502,
    idv: 135090,
    policy: "Third Party",
  },

  // bajaj

  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2019",
    premiumAmount: 700,
    idv: 20000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2019",
    premiumAmount: 500,
    idv: 95000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2020",
    premiumAmount: 1050,
    idv: 30900,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: BikeMaker.bajaj,
    model: BajajModels.pulsar,
    year: "2020",
    premiumAmount: 950,
    idv: 25900,
    policy: "Third Party",
  },

  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2019",
    premiumAmount: 1050,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2019",
    premiumAmount: 2042,
    idv: 31300,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2020",
    premiumAmount: 950,
    idv: 32300,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: BikeMaker.bajaj,
    model: BajajModels.platina,
    year: "2020",
    premiumAmount: 742,
    idv: 91300,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2019",
    premiumAmount: 900,
    idv: 80000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2019",
    premiumAmount: 840,
    idv: 70300,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2020",
    premiumAmount: 9100,
    idv: 200000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.dominar,
    year: "2020",
    premiumAmount: 520,
    idv: 91300,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2019",
    premiumAmount: 702,
    idv: 23090,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2019",
    premiumAmount: 802,
    idv: 63090,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2020",
    premiumAmount: 902,
    idv: 58090,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: BikeMaker.bajaj,
    model: BajajModels.CT,
    year: "2020",
    premiumAmount: 2002,
    idv: 91009,
    policy: "Third Party",
  },
];
