export const enum CarMaker {
  honda = "Honda",
  hyundai = "Hyundai",
  skoda = "Skoda",
}
export const enum HondaModels {
  amaze = "Amaze",
  city = "City",
  civic = "Civic",
  jazz = "Jazz",
}
export const enum HyundaiModels {
  creta = "Creta",
  venue = "venue",
  verna = "Verna",
  aura = "Aura",
}

export const enum SkodaModels {
  slavia = "Slavia",
  octavia = "Octavia",
  superb = "Superb",
  kodiaq = "Kodiaq",
}
export const CarInsuranceDekho = [
  {
    provider: "bajaj",
    maker: CarMaker.honda,
    model: HondaModels.civic,
    year: "2019",
    premiumAmount: 7000,
    idv: 200000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.honda,
    model: HondaModels.civic,
    year: "2019",
    premiumAmount: 5000,
    idv: 150000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: CarMaker.honda,
    model: HondaModels.civic,
    year: "2020",
    premiumAmount: 8500,
    idv: 289000,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: CarMaker.honda,
    model: HondaModels.civic,
    year: "2020",
    premiumAmount: 6500,
    idv: 159000,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: CarMaker.honda,
    model: HondaModels.city,
    year: "2019",
    premiumAmount: 9500,
    idv: 323000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.honda,
    model: HondaModels.city,
    year: "2019",
    premiumAmount: 7420,
    idv: 213000,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: CarMaker.honda,
    model: HondaModels.city,
    year: "2020",
    premiumAmount: 9500,
    idv: 323000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.honda,
    model: HondaModels.city,
    year: "2020",
    premiumAmount: 7420,
    idv: 213000,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.amaze,
    year: "2019",
    premiumAmount: 9000,
    idv: 200000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.amaze,
    year: "2019",
    premiumAmount: 8400,
    idv: 103000,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.amaze,
    year: "2020",
    premiumAmount: 9100,
    idv: 200000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.amaze,
    year: "2020",
    premiumAmount: 8200,
    idv: 113000,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: CarMaker.honda,
    model: HondaModels.jazz,
    year: "2019",
    premiumAmount: 7020,
    idv: 230900,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.honda,
    model: HondaModels.jazz,
    year: "2019",
    premiumAmount: 4020,
    idv: 130900,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.jazz,
    year: "2020",
    premiumAmount: 8020,
    idv: 280900,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.jazz,
    year: "2020",
    premiumAmount: 5020,
    idv: 1350900,
    policy: "Third Party",
  },

  // HYUNDAI

  {
    provider: "bajaj",
    maker: CarMaker.hyundai,
    model: HyundaiModels.creta,
    year: "2019",
    premiumAmount: 7000,
    idv: 200000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.hyundai,
    model: HyundaiModels.creta,
    year: "2019",
    premiumAmount: 5000,
    idv: 150000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: CarMaker.hyundai,
    model: HyundaiModels.creta,
    year: "2020",
    premiumAmount: 8500,
    idv: 289000,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: CarMaker.hyundai,
    model: HyundaiModels.creta,
    year: "2020",
    premiumAmount: 6500,
    idv: 159000,
    policy: "Third Party",
  },

  {
    provider: "Sriram",
    maker: CarMaker.hyundai,
    model: HyundaiModels.venue,
    year: "2019",
    premiumAmount: 9500,
    idv: 323000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.hyundai,
    model: HyundaiModels.venue,
    year: "2019",
    premiumAmount: 7420,
    idv: 213000,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: CarMaker.hyundai,
    model: HyundaiModels.venue,
    year: "2020",
    premiumAmount: 9500,
    idv: 323000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.hyundai,
    model: HyundaiModels.venue,
    year: "2020",
    premiumAmount: 7420,
    idv: 213000,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.verna,
    year: "2019",
    premiumAmount: 9000,
    idv: 200000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.verna,
    year: "2019",
    premiumAmount: 8400,
    idv: 103000,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.verna,
    year: "2020",
    premiumAmount: 9100,
    idv: 200000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.verna,
    year: "2020",
    premiumAmount: 8200,
    idv: 113000,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: CarMaker.hyundai,
    model: HyundaiModels.aura,
    year: "2019",
    premiumAmount: 7020,
    idv: 230900,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.hyundai,
    model: HyundaiModels.aura,
    year: "2019",
    premiumAmount: 4020,
    idv: 130900,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.aura,
    year: "2020",
    premiumAmount: 8020,
    idv: 280900,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.aura,
    year: "2020",
    premiumAmount: 5020,
    idv: 1350900,
    policy: "Third Party",
  },

  // SKODA

  {
    provider: "bajaj",
    maker: CarMaker.skoda,
    model: SkodaModels.kodiaq,
    year: "2019",
    premiumAmount: 7000,
    idv: 200000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.skoda,
    model: SkodaModels.kodiaq,
    year: "2019",
    premiumAmount: 5000,
    idv: 150000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: CarMaker.skoda,
    model: SkodaModels.kodiaq,
    year: "2020",
    premiumAmount: 8500,
    idv: 289000,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: CarMaker.skoda,
    model: SkodaModels.kodiaq,
    year: "2020",
    premiumAmount: 6500,
    idv: 159000,
    policy: "Third Party",
  },

  {
    provider: "Sriram",
    maker: CarMaker.skoda,
    model: SkodaModels.octavia,
    year: "2019",
    premiumAmount: 9500,
    idv: 323000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.skoda,
    model: SkodaModels.octavia,
    year: "2019",
    premiumAmount: 7420,
    idv: 213000,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: CarMaker.skoda,
    model: SkodaModels.octavia,
    year: "2020",
    premiumAmount: 9500,
    idv: 323000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.skoda,
    model: SkodaModels.octavia,
    year: "2020",
    premiumAmount: 7420,
    idv: 213000,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.slavia,
    year: "2019",
    premiumAmount: 9000,
    idv: 200000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.slavia,
    year: "2019",
    premiumAmount: 8400,
    idv: 103000,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.slavia,
    year: "2020",
    premiumAmount: 9100,
    idv: 200000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.slavia,
    year: "2020",
    premiumAmount: 8200,
    idv: 113000,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: CarMaker.skoda,
    model: SkodaModels.superb,
    year: "2019",
    premiumAmount: 7020,
    idv: 230900,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.skoda,
    model: SkodaModels.superb,
    year: "2019",
    premiumAmount: 4020,
    idv: 130900,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.superb,
    year: "2020",
    premiumAmount: 8020,
    idv: 280900,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.superb,
    year: "2020",
    premiumAmount: 5020,
    idv: 1350900,
    policy: "Third Party",
  },
];

// POLICY BAZARRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRr

export const CarPolicyBazar = [
  {
    provider: "bajaj",
    maker: CarMaker.honda,
    model: HondaModels.civic,
    year: "2019",
    premiumAmount: 7800,
    idv: 290000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.honda,
    model: HondaModels.civic,
    year: "2019",
    premiumAmount: 6000,
    idv: 170000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: CarMaker.honda,
    model: HondaModels.civic,
    year: "2020",
    premiumAmount: 8200,
    idv: 287000,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: CarMaker.honda,
    model: HondaModels.civic,
    year: "2020",
    premiumAmount: 6600,
    idv: 164000,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: CarMaker.honda,
    model: HondaModels.city,
    year: "2019",
    premiumAmount: 8500,
    idv: 223000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.honda,
    model: HondaModels.city,
    year: "2019",
    premiumAmount: 6420,
    idv: 113000,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: CarMaker.honda,
    model: HondaModels.city,
    year: "2020",
    premiumAmount: 9800,
    idv: 353000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.honda,
    model: HondaModels.city,
    year: "2020",
    premiumAmount: 7620,
    idv: 253000,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.amaze,
    year: "2019",
    premiumAmount: 7000,
    idv: 120000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.amaze,
    year: "2019",
    premiumAmount: 9400,
    idv: 193000,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.amaze,
    year: "2020",
    premiumAmount: 9600,
    idv: 260000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.amaze,
    year: "2020",
    premiumAmount: 8100,
    idv: 103000,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: CarMaker.honda,
    model: HondaModels.jazz,
    year: "2019",
    premiumAmount: 6020,
    idv: 130900,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.honda,
    model: HondaModels.jazz,
    year: "2019",
    premiumAmount: 3020,
    idv: 100900,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.jazz,
    year: "2020",
    premiumAmount: 7020,
    idv: 260900,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.jazz,
    year: "2020",
    premiumAmount: 4020,
    idv: 1050900,
    policy: "Third Party",
  },

  // HYUNDAI

  {
    provider: "bajaj",
    maker: CarMaker.hyundai,
    model: HyundaiModels.creta,
    year: "2019",
    premiumAmount: 7500,
    idv: 230000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.hyundai,
    model: HyundaiModels.creta,
    year: "2019",
    premiumAmount: 4000,
    idv: 120000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: CarMaker.hyundai,
    model: HyundaiModels.creta,
    year: "2020",
    premiumAmount: 9500,
    idv: 389000,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: CarMaker.hyundai,
    model: HyundaiModels.creta,
    year: "2020",
    premiumAmount: 7500,
    idv: 179000,
    policy: "Third Party",
  },

  {
    provider: "Sriram",
    maker: CarMaker.hyundai,
    model: HyundaiModels.venue,
    year: "2019",
    premiumAmount: 8500,
    idv: 223000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.hyundai,
    model: HyundaiModels.venue,
    year: "2019",
    premiumAmount: 6420,
    idv: 113000,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: CarMaker.hyundai,
    model: HyundaiModels.venue,
    year: "2020",
    premiumAmount: 8500,
    idv: 303000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.hyundai,
    model: HyundaiModels.venue,
    year: "2020",
    premiumAmount: 5420,
    idv: 113000,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.verna,
    year: "2019",
    premiumAmount: 8000,
    idv: 170000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.verna,
    year: "2019",
    premiumAmount: 6000,
    idv: 103000,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.verna,
    year: "2020",
    premiumAmount: 9900,
    idv: 280000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.verna,
    year: "2020",
    premiumAmount: 8000,
    idv: 103000,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: CarMaker.hyundai,
    model: HyundaiModels.aura,
    year: "2019",
    premiumAmount: 7820,
    idv: 270900,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.hyundai,
    model: HyundaiModels.aura,
    year: "2019",
    premiumAmount: 4520,
    idv: 150900,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.aura,
    year: "2020",
    premiumAmount: 8320,
    idv: 290900,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.aura,
    year: "2020",
    premiumAmount: 5120,
    idv: 1250900,
    policy: "Third Party",
  },

  // SKODA

  {
    provider: "bajaj",
    maker: CarMaker.skoda,
    model: SkodaModels.kodiaq,
    year: "2019",
    premiumAmount: 7700,
    idv: 250000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.skoda,
    model: SkodaModels.kodiaq,
    year: "2019",
    premiumAmount: 5100,
    idv: 160000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: CarMaker.skoda,
    model: SkodaModels.kodiaq,
    year: "2020",
    premiumAmount: 9500,
    idv: 309000,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: CarMaker.skoda,
    model: SkodaModels.kodiaq,
    year: "2020",
    premiumAmount: 6000,
    idv: 150000,
    policy: "Third Party",
  },

  {
    provider: "Sriram",
    maker: CarMaker.skoda,
    model: SkodaModels.octavia,
    year: "2019",
    premiumAmount: 10500,
    idv: 393000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.skoda,
    model: SkodaModels.octavia,
    year: "2019",
    premiumAmount: 7620,
    idv: 283000,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: CarMaker.skoda,
    model: SkodaModels.octavia,
    year: "2020",
    premiumAmount: 9500,
    idv: 343000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.skoda,
    model: SkodaModels.octavia,
    year: "2020",
    premiumAmount: 7120,
    idv: 223000,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.slavia,
    year: "2019",
    premiumAmount: 8500,
    idv: 140000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.slavia,
    year: "2019",
    premiumAmount: 7800,
    idv: 100000,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.slavia,
    year: "2020",
    premiumAmount: 9200,
    idv: 210000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.slavia,
    year: "2020",
    premiumAmount: 8000,
    idv: 103000,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: CarMaker.skoda,
    model: SkodaModels.superb,
    year: "2019",
    premiumAmount: 7000,
    idv: 230000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.skoda,
    model: SkodaModels.superb,
    year: "2019",
    premiumAmount: 4120,
    idv: 134900,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.superb,
    year: "2020",
    premiumAmount: 8120,
    idv: 290900,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.superb,
    year: "2020",
    premiumAmount: 5120,
    idv: 160900,
    policy: "Third Party",
  },
];

export const CarHdfcErgo = [
  {
    provider: "bajaj",
    maker: CarMaker.honda,
    model: HondaModels.civic,
    year: "2019",
    premiumAmount: 6560,
    idv: 187000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.honda,
    model: HondaModels.civic,
    year: "2019",
    premiumAmount: 4500,
    idv: 110000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: CarMaker.honda,
    model: HondaModels.civic,
    year: "2020",
    premiumAmount: 8300,
    idv: 270000,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: CarMaker.honda,
    model: HondaModels.civic,
    year: "2020",
    premiumAmount: 6600,
    idv: 140000,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: CarMaker.honda,
    model: HondaModels.city,
    year: "2019",
    premiumAmount: 9300,
    idv: 310000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.honda,
    model: HondaModels.city,
    year: "2019",
    premiumAmount: 6420,
    idv: 198000,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: CarMaker.honda,
    model: HondaModels.city,
    year: "2020",
    premiumAmount: 10100,
    idv: 354000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.honda,
    model: HondaModels.city,
    year: "2020",
    premiumAmount: 7720,
    idv: 256000,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.amaze,
    year: "2019",
    premiumAmount: 9900,
    idv: 290000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.amaze,
    year: "2019",
    premiumAmount: 8400,
    idv: 145000,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.amaze,
    year: "2020",
    premiumAmount: 9100,
    idv: 230000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.amaze,
    year: "2020",
    premiumAmount: 8200,
    idv: 159000,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: CarMaker.honda,
    model: HondaModels.jazz,
    year: "2019",
    premiumAmount: 7430,
    idv: 157900,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.honda,
    model: HondaModels.jazz,
    year: "2019",
    premiumAmount: 4320,
    idv: 95000,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.jazz,
    year: "2020",
    premiumAmount: 7990,
    idv: 270900,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.honda,
    model: HondaModels.jazz,
    year: "2020",
    premiumAmount: 5220,
    idv: 145090,
    policy: "Third Party",
  },

  // HYUNDAI

  {
    provider: "bajaj",
    maker: CarMaker.hyundai,
    model: HyundaiModels.creta,
    year: "2019",
    premiumAmount: 7000,
    idv: 219000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.hyundai,
    model: HyundaiModels.creta,
    year: "2019",
    premiumAmount: 5400,
    idv: 190000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: CarMaker.hyundai,
    model: HyundaiModels.creta,
    year: "2020",
    premiumAmount: 8560,
    idv: 299000,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: CarMaker.hyundai,
    model: HyundaiModels.creta,
    year: "2020",
    premiumAmount: 6550,
    idv: 164000,
    policy: "Third Party",
  },

  {
    provider: "Sriram",
    maker: CarMaker.hyundai,
    model: HyundaiModels.venue,
    year: "2019",
    premiumAmount: 9350,
    idv: 312000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.hyundai,
    model: HyundaiModels.venue,
    year: "2019",
    premiumAmount: 7340,
    idv: 245000,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: CarMaker.hyundai,
    model: HyundaiModels.venue,
    year: "2020",
    premiumAmount: 9500,
    idv: 334000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.hyundai,
    model: HyundaiModels.venue,
    year: "2020",
    premiumAmount: 7420,
    idv: 224000,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.verna,
    year: "2019",
    premiumAmount: 9300,
    idv: 220000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.verna,
    year: "2019",
    premiumAmount: 8200,
    idv: 278000,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.verna,
    year: "2020",
    premiumAmount: 9030,
    idv: 323000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.verna,
    year: "2020",
    premiumAmount: 8230,
    idv: 234000,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: CarMaker.hyundai,
    model: HyundaiModels.aura,
    year: "2019",
    premiumAmount: 7020,
    idv: 210900,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.hyundai,
    model: HyundaiModels.aura,
    year: "2019",
    premiumAmount: 4020,
    idv: 120900,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.aura,
    year: "2020",
    premiumAmount: 8120,
    idv: 281900,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.hyundai,
    model: HyundaiModels.aura,
    year: "2020",
    premiumAmount: 5120,
    idv: 145090,
    policy: "Third Party",
  },

  // SKODA

  {
    provider: "bajaj",
    maker: CarMaker.skoda,
    model: SkodaModels.kodiaq,
    year: "2019",
    premiumAmount: 7100,
    idv: 220000,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.skoda,
    model: SkodaModels.kodiaq,
    year: "2019",
    premiumAmount: 5340,
    idv: 167000,
    policy: "Third Party",
  },
  {
    provider: "digit",
    maker: CarMaker.skoda,
    model: SkodaModels.kodiaq,
    year: "2020",
    premiumAmount: 8500,
    idv: 289000,
    policy: "Comprehensive",
  },
  {
    provider: "digit",
    maker: CarMaker.skoda,
    model: SkodaModels.kodiaq,
    year: "2020",
    premiumAmount: 7500,
    idv: 259000,
    policy: "Third Party",
  },

  {
    provider: "Sriram",
    maker: CarMaker.skoda,
    model: SkodaModels.octavia,
    year: "2019",
    premiumAmount: 9200,
    idv: 323000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.skoda,
    model: SkodaModels.octavia,
    year: "2019",
    premiumAmount: 7220,
    idv: 203000,
    policy: "Third Party",
  },
  {
    provider: "Sriram",
    maker: CarMaker.skoda,
    model: SkodaModels.octavia,
    year: "2020",
    premiumAmount: 8500,
    idv: 310000,
    policy: "Comprehensive",
  },
  {
    provider: "Sriram",
    maker: CarMaker.skoda,
    model: SkodaModels.octavia,
    year: "2020",
    premiumAmount: 5220,
    idv: 113000,
    policy: "Third Party",
  },

  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.slavia,
    year: "2019",
    premiumAmount: 9100,
    idv: 345000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.slavia,
    year: "2019",
    premiumAmount: 8140,
    idv: 313000,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.slavia,
    year: "2020",
    premiumAmount: 9100,
    idv: 340000,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.slavia,
    year: "2020",
    premiumAmount: 8200,
    idv: 345000,
    policy: "Third Party",
  },

  {
    provider: "bajaj",
    maker: CarMaker.skoda,
    model: SkodaModels.superb,
    year: "2019",
    premiumAmount: 7120,
    idv: 231900,
    policy: "Comprehensive",
  },
  {
    provider: "bajaj",
    maker: CarMaker.skoda,
    model: SkodaModels.superb,
    year: "2019",
    premiumAmount: 4120,
    idv: 131900,
    policy: "Third Party",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.superb,
    year: "2020",
    premiumAmount: 8120,
    idv: 290900,
    policy: "Comprehensive",
  },
  {
    provider: "United India Insurance",
    maker: CarMaker.skoda,
    model: SkodaModels.superb,
    year: "2020",
    premiumAmount: 5020,
    idv: 130900,
    policy: "Third Party",
  },
];
